99: 未知错误
100: 需要权限
101: 资源不存在
102: 参数不全
103: 上传的图片太大
104: 参数为空
105: 图片格式不支持
106: 参数错误
107: 用户已存在
108: 用户不存在
109: 账号密码错误
110: 手机验证错误或已过期
111: 查询成功,用户不存在
112: 查询失败
113: 查询成功,无结果
114: 未登录
115: 班级名称已被使用，创建班级失败
116: 班级未发布，不能添加学员
117: 班级不存在
118: 用户不存在
119: 班级已存在，创建失败
0: 查询成功