acme_hello_homepage:
    path:     /hello/{name}
    defaults: { _controller: AcmeHelloBundle:Default:index }

acme_random:
    path:     /rand/{limit}
    defaults: { _controller: AcmeHelloBundle:Random:index }
